# Generated by Django 5.0.1 on 2024-01-24 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('prix_de_vente', models.FloatField()),
                ('prix_réduit', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('application_de_production', models.TextField(default='')),
                ('categorie', models.CharField(choices=[('PC', 'Pouf en cuir'), ('OC', 'Oreillers en cuir'), ('TC', 'Têtes de lit en cuir'), ('SC', 'sac')], max_length=2000)),
                ('produit_image', models.ImageField(upload_to='produit')),
                ('stock', models.CharField(choices=[('disponible ', 'disponible '), (' Réapprovisionné ', ' Réapprovisionné '), ('Quantités limitées  ', 'Quantités limitées  ')], max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('localisation', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('province', models.CharField(choices=[('Chaouia-Ouardigha ', 'Chaouia-Ouardigha '), (' Doukkala-Abda ', ' Doukkala-Abda '), ('Fès-Boulemane  ', 'Fès-Boulemane  '), (' Gharb-Chrarda-Beni Hssen ', 'Gharb-Chrarda-Beni Hssen  '), ('Grand Casablanca  ', ' Grand Casablanca '), ('Guelmim-Es Semara  ', 'Guelmim-Es Semara  '), ('Laâyoune-Boujdour-Sakia el Hamra  ', 'Laâyoune-Boujdour-Sakia el Hamra  '), ('Marrakech-Tensift-Al Haouz  ', ' Marrakech-Tensift-Al Haouz '), ('Meknès-Tafilalet  ', 'Meknès-Tafilalet  '), ('Oriental  ', 'LOriental  '), (' Oued ed Dahab-Lagouira ', ' Oued ed Dahab-Lagouira '), ('Rabat-Salé-Zemmour-Zaër ', 'Rabat-Salé-Zemmour-Zaër '), ('Souss-Massa-Drâa  ', ' Souss-Massa-Drâa '), ('Tadla-Azilal  ', 'Tadla-Azilal  '), ('Tanger-Tétouan ', 'Tanger-Tétouan '), ('Wilaya de Tanger ', ' Wilaya de Tanger'), (' Wilaya de Tétouan', 'Wilaya de Tétouan '), ('Taza-Al Hoceïma-Taounate ', 'Taza-Al Hoceïma-Taounate ')], max_length=100)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
            ],
        ),
        migrations.CreateModel(
            name='favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
            ],
        ),
        migrations.CreateModel(
            name='adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
            ],
        ),
    ]
